name: whatsapp_share_example
description: Demonstrates how to use the whatsapp_share plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  screenshot: ^0.1.1
  documents_picker: ^1.0.0
  path_provider: ^1.3.0
  image_picker: ^0.6.2+3


  whatsapp_share:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
